name: Run Unittests

on:
  push:
    branches: [ main ]

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Unittest
      run: |
        python -m unittest -v test/unit.py
